#!/bin/bash

set -e
set -o pipefail
set -u

scriptdir=`dirname "$(readlink -f "$0")"`
export PERL5LIB=$scriptdir/lib:${PERL5LIB:-}

# assert variables are set
[ -n "$LUCYNDEX_LANG" ]
[ -n "$LUCY_INDEX_PATH" ]
true "${TRACKRUN_LAST_SUCCESSFUL_STARTED?Need to be run by trackrun(1)}"

echo "indexing Emails since ${TRACKRUN_LAST_SUCCESSFUL_STARTED:-forever}" >&2

strip_leading_dot_slash()
{
	cut -c 3-
}

find . \( \
		-type d \
		\( -iname spam -or -iname trash -or -iname kuka -or -iname 'törölt elemek' -or -name .getmail \) \
		-prune -false \
	\) -or \( \
		-type f \
		-newermt "$TRACKRUN_LAST_SUCCESSFUL_STARTED" \
		! -name maildirfs.cache \
	\) |\
strip_leading_dot_slash |\
"$scriptdir"/mkdoc |\
"$scriptdir"/lucyndex "$LUCY_INDEX_PATH"
