#!/bin/bash

set -e
set -o pipefail
set -u

selfdir=`dirname "$(readlink -f "$0")"`
export PERL5LIB=$selfdir/lib:${PERL5LIB:-}

timestampfile=$LUCY_INDEX_PATH/last-indexing-started
date -R > "$timestampfile.new"

if [ -s "$timestampfile" ]
then
	echo "indexing Emails since $(cat "$timestampfile")" >&2
fi

find "$MAILS_ROOT_PATH" \( -type d \( \
	-iname spam -or -iname trash -or -iname kuka -or -iname 'törölt elemek' \
	-or -name .getmail \
	\) -prune -false \) -or \( \
	-newer "$timestampfile" \
	-type f \
	! -name maildirfs.cache \
	\) |\
"$selfdir"/mkdoc |\
"$selfdir"/lucyndex "$LUCY_INDEX_PATH"

mv "$timestampfile.new" "$timestampfile"
